# .github/workflows/main.yml

name: Fly Deploy

on:
  push:
    branches:
      - main # Or whatever your main branch is

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/fly-pr-review-apps@1
        with:
          fly_api_token: ${{ secrets.FLY_API_TOKEN }}
          fly_app_name: 'skyeupload' # Your Fly.io app name here
